workflows:
  maui-android-build:
    name: Build .NET MAUI Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install .NET SDK 9.0
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 9.0 --install-dir $DOTNET_PATH
      - name: Install .NET MAUI workloads
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload restore
          $DOTNET workload install maui maui-android maui-ios
      - name: Restore MauiApp.Demo project
        script: |
          $DOTNET restore MauiApp.Demo/MauiApp.Demo.csproj
      - name: Build MauiApp.Demo project for Android
        script: |
          $DOTNET build MauiApp.Demo/MauiApp.Demo.csproj -c Release -f net9.0-android --no-restore
    artifacts:
      - '**/*.apk'
      - '**/*.aab'

  maui-ios-simulator-build:
    name: Build .NET MAUI iOS Simulator
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install .NET SDK 7.0
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 7.0 --install-dir $DOTNET_PATH
      - name: Install .NET MAUI workloads
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload restore
          $DOTNET workload install maui maui-ios
      - name: Restore MauiApp.Demo project
        script: |
          $DOTNET restore MauiApp.Demo/MauiApp.Demo.csproj
      - name: Build MauiApp.Demo project for iOS Simulator
        script: |
          $DOTNET build MauiApp.Demo/MauiApp.Demo.csproj -c Debug -f net7.0-ios --no-restore -o ./artifacts
    artifacts:
      - ./artifacts/*.app